---
title: Brix Blog - private pension plan for You.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
description: Brix Blog - private pension plan for You.
url: http://www.brixpension.com
author:
  name: Brix Finance
  email: bernard@brixpension.com
  url: http://www.jacoporabolini.com
baseurl: "/"
markdown: kramdown
source: "."
destination: "./_site"
permalink: "/:title"
paginate: 8
paginate_path: "/page:num/"
gems:
- jekyll-paginate
custom_header: true
custom_nav_footer: false
reverse: false
